controller_manager:
  ros__parameters:
    update_rate: 100

joint_state_broadcaster:
  ros__parameters:
    update_rate: 50
    type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - joint1
      - joint2

gripper_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - gripper_left_finger_joint
